services:
  recommender_service:
    build: "./recommender_service"
    volumes:
      - type: "bind"
        source: "./data"
        target: "/opt/data"
    environment:
      # DATA_DIR_URL: "/opt/data"
      RECOMMENDER_PORT: 8080
      USERS_DATA_URL: "/opt/data/Users.csv"
      RATINGS_DATA_URL: "/opt/data/trans_ratings.csv"
      BOOKS_DATA_URL:  "/opt/data/trans_books.csv"

  redis:
    image: "redis:alpine"

  gateway:
    build: "./gateway"
    environment:
      recommender_service_url: 'recommender_service'
      recommender_service_port: 8080
  webserver:
    build: "./webserver"
    environment:
      gateway_service_url: 'gateway'
      gateway_service_port: 5000
    ports: 
      - "80:80"